server:
  port: 8081

spring:
  application:
    name: fishsnap-gateway

  cloud:
    gateway:
      routes:
        - id: fishsnap-app
          uri: http://localhost:9090
          predicates:
            - Path=/fsnap/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true